### PR TITLE
Fix bug stored XSS when rendering table and flash message

### PR DESCRIPTION
**Pull request by noobpk**
Disclosure: https://huntr.dev/bounties/80960445-5a6b-4deb-955f-26a0cd7bde2b

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by noobpk** [comment]
@marcoax can you validate my report on huntr. [https://huntr.dev/bounties/80960445-5a6b-4deb-955f-26a0cd7bde2b/](https://huntr.dev/bounties/80960445-5a6b-4deb-955f-26a0cd7bde2b/)

**Comment by JamieSlome** [comment]
@marcoax - thanks for taking the time to address this!

Can you confirm if this report disclosed by @noobpk helped infer the security improvement here?

Cheers! 🎉

**Comment by marcoax** [comment]
Hi 
Yes

**Comment by noobpk** [comment]
@marcoax can you validate my report on huntr. https://huntr.dev/bounties/80960445-5a6b-4deb-955f-26a0cd7bde2b/ ^^!

**Pull request merged**
